services:

        
  hoj-mysql:
    image: ${HBUTOJ_MYSQL_IMAGE_PREFIX:-${HBUTOJ_IMAGE_PREFIX:-ghcr.io/1650041940}}/${HBUTOJ_MYSQL_IMAGE:-hbutoj_database}:${HBUTOJ_IMAGE_TAG:-latest}
    container_name: hoj-mysql
    restart: always
    deploy:
      resources:
        limits:
          memory: ${MYSQL_CHECKER_MYSQL_MEM_LIMIT:-512M}
    mem_limit: ${MYSQL_CHECKER_MYSQL_MEM_LIMIT:-512M}
    volumes:
      - ./hoj/data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-hoj123456} # mysql数据库root账号的密码
      - TZ=Asia/Shanghai
      - NACOS_USERNAME=${NACOS_USERNAME:-root} # 后续nacos所用管理员账号
      - NACOS_PASSWORD=${NACOS_PASSWORD:-hoj123456} # 后续nacos所用管理员密码
    ports:
      - ${MYSQL_PORT:-3306}:3306
    healthcheck:
      test: mysql --user=root --password=${MYSQL_ROOT_PASSWORD:-hoj123456} -e 'select * from nacos.users;'
      interval: 2s
      timeout: 20s
      retries: 10
  
  hoj-mysql-checker:
    image: ${HBUTOJ_MYSQL_CHECKER_IMAGE_PREFIX:-${HBUTOJ_IMAGE_PREFIX:-ghcr.io/1650041940}}/${HBUTOJ_MYSQL_CHECKER_IMAGE:-hbutoj_database_checker}:${HBUTOJ_IMAGE_TAG:-latest}
    container_name: hoj-mysql-checker
    deploy:
      resources:
        limits:
          memory: ${MYSQL_CHECKER_CHECKER_MEM_LIMIT:-128M}
    mem_limit: ${MYSQL_CHECKER_CHECKER_MEM_LIMIT:-128M}
    depends_on:
      - hoj-mysql
    links:
      - hoj-mysql:mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-hoj123456}